# Generated by Django 5.1.6 on 2025-02-17 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='finished_date_played',
            field=models.DateTimeField(null=True, verbose_name='Finalizado em'),
        ),
    ]
