# Generated by Django 5.1.6 on 2025-02-11 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_managers_user_date_joined_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avatars/blank-profile-picture.png', upload_to='avatars/', verbose_name='Avatar'),
        ),
    ]
